language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis poetry
script: tox
deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: pgZ84/nfO3FtgCoWEbmW60LdSPqaDY3fFdkVMYiUmzgakzYqQJMuhb+cY3lJw7hNxomGujW447vqWswZ5VtJSrEk6no3bBnE0JwcP5IrdizL04KRAhIfzxhDiI2y9dOiHXbq4RKzLo80FyydJqndO1QFtWBQSKa9uDUBorrVFltQ+CTBhGYQvtW+5hgViwXXu0K5DmPUIzjI+b+yrxRh0nAGqs8QJSCn0VvX/GVT28d/2DOnzXyDOiJA7uRN5QTAGdzSvDXkxNMsoo2S/2qWlNKbwPWfb2Bma5s0Iz/ZjQsc2+7Ryn7XOos+H1XGlEpOKc6nqqBCAw+qQmkaPtsrpEBbbk4XQNoPNoC3RuZJYSR3e5DJSxRQTo422vnuxzz3R5fjpsFVTWERt1kD1UHCflYz010JI0450cBpxx5DYgz/rYMDqYw80CQ3XNkkwkTXURxinFU+zgU1FXW8Anvr1ZYXKUZ9iUJQaBQ5zijzCd3Fk98mPSdH2FThb3miago/FINT9qXRJQepehdpVDQo1mVABNvpvk7xxCBrB3ffbpQJqlr2muDW4fkohtDMag+KkjGmaza7WLQC6WPYvgVaofdT1xjiDeMkK1mGSM0wcrmj1NlTgvBMwBNF4QE24XIhW1GLR4GdXGI1SALjK7BR3hiPG+TLeSj8ylNfQeQHpOw=
  on:
    tags: true
    repo: fwallacevt/simple-redis-lock
    python: 3.8
