language: python
python:
- 3.8
- 3.7
services:
  - redis-server
install: pip install -U tox-travis poetry
script: tox
before_deploy:
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
- poetry build
deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: fwallacevt/redis-heartbeat-lock
    python:
      - 3.7
      - 3.8
env:
  global:
  - secure: dCRKpTfiGZP/44fto6HbC7NxXmlmUBWTNKoW76D94Dpwz/gUaZYi2EfQUSCjzGb0uoywwKJUiOU/lRAd2DYETzAnH5m/fhrCP7XB8x3/Degf9ty6tIr3MjeAVfXJbpvWxWESUlFNL9AhAWk2PGR1OYxf2KEZDRWRbRZt62ECtN1QKbO7LUEckyroP37VDAhBqsBWa/YMGN6RkiXBxDOzNlbc7iykM7KHpJj0+K4jtibyL6lnRMcsUuJER8IoIPpPjXPUOXksfgo19jE2JrAB24PVqOBhO9ou0ye5K1hgMzYMbb1duYubhiBo7B6iHHehAwZZbyfi3I1Y/zWlBYFlpku2dW8icdaF/DH4Bfv9K5c0D4DacAHjlLXDpel9F8pkPqBRlYB9pL6VrXH6XS4Df6EB+3nD50uoE+RRtrAlaT0/bx4hGg8opRKctnWKYqw4mXxqxKgkbEHID2tJQXVtYEJEj+jtf4SYzVyX5Cyj1na/zVqfKKj2hEKBfdii+nJRYt8XZJ2/OdKjyy/RtJUcCrDfMJDG9QLIlwp8naIcXU6Evp7ipTz3p7yxgSEh5pSl32yNYqjL0URkTuWTAs2YkBrIP4+p2GkoHW5FlI9sTouCUziCMficHu2gQF1mE5ht5bTk2t2XTrhQIOiAVOTtI0y3S0mdY58o6NSofvBLx/c=
  - secure: t/3/ZVE5rbp3pjq37fBj0XdSVwRZ3F6iF1Pk5Mz3J/3SbiNJQL+2na3xQsX+eUSdcJhV53sqPghHHQiEVAzqHbjEAijar27q/V3/poxXNrM21S81MzjOtPSiMP0uvoXMfNWJ35kyiKcRdDVft+iSn+WI+X3mdHBrNZczaKAT2x/evSS0zw6NYGHm6Z7WeEq2LTN4q8RTwHVqNnsEAu6mNi+Ra5mj+fk4XurbqXBehlSG+LtvqqUk2aJgBaz82ymPnPUuHEid7Cd4jc3gqGcDYCj6+ItFYZWX+NqqHMzkL++0fcamf+5cjvBJrUzyN+Z/Jv21jHi/WSXImC9yutB467oRZ8sv6rKWdXkay70Zs85jng0ytN/bqtKXcdL6bEzLFLkyCp0pCsF0N9/GS0Ddq0mPvw+RAM9G7rcx8QekDqMmZx3Tge8NDWJcNKD26/xHA2L5D0Dq3ZvyF+G0H1da9GBAuCuAHERyXgPvaHdHYUnT17zkObSniXRz47fFwn5ADN3cAprLEH8P9T2LK5dWG3Hz40BysC71AFnpz/EDUKsUQW79oYuvvrJACb2ocnVMVKrPyKsxQg7DD+dxb6TfBtqDcQ8Dv8T8cPEcu5cvjLrAjHedKXy1xltE1C8TrMQM44rQ/bfneN8N54hbLhIY+j2gG8/Do4fd73AaZJweAkk=
