language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis poetry
script: tox
deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: uaqFLgF9F/dMKIuN6pTK8IPbIYVGW00il1jITOFe89uO62pf0fIkm7dDg03+L6Rozi8HkgxnxSpPIfTVYQjbvycPjy/vYnfNOSxEsynBCzV+qgo24LvyRoXaxZbLrzyyq7u/+IR5ynn2sj+2K2TbNzPii9mfEhek9l9SF1KKG+ldREp6fh3yYvxOoB65dCkdlabpOfuDVKrD3ynr3GqJ4qaz4HvjgkDrXEe57cCy1GKq327VxTAjz2G9CNoOmluUhSwvhQNLI5ECTBGJFf8N2TjbSPt2RMHqgtrhrnKmHl/kV+QUM6x0wdkhglpOY1p9avM1bSBKToc9ffx/ZuINhJ9EZzgv++zzOs/MVr6gpj0hFvour2TuXgreei+0LtvqZZkgmI/f05yHe1ozZ6NOLhVyqy69hOsKtjTMZ/nYxxSPz20uiZGZ1igOlc6ZEiVW7CR7bRBQXMqQIYmwgGJrPlgYKYZMtNLbNyldNryeJ9qKouK//WhClXPTmS3oj+WclDMC+h4F5dlyoEKp8zwdaUmjxUzZNohpDhI4yD8xMcWvwh60Al27OgcpdHy0FDGzHuWPfAtr1qRYwvcdBVwQUbbEMaR5qBMBrmt4pGGRdFtrCSzH2c2tHMYOQtk0bGqVvAxqe0hgoyisy8PDr/unrga9SRomlZ0dIvOv9lsZlOE=
  on:
    tags: true
    repo: fwallacevt/simple_redis_lock
    python: 3.8
